Add test for SSD, parameterize test for MMR.
smartnews/rsdiv pull request #48
Opened 2022-07-28 18:17 UTC by JyChang012

2022-07-30 15:10 UTC, JyChang012 commented
> Yes, from my VSCode's mypy checker:
> 
> ```
> Signature of "rerank" incompatible with supertype "BaseReranker"
> ```

pre-commit also runs mypy. Why doesn't the error show?

2022-08-01 02:32 UTC, yinsn commented on src/rsdiv/diversity/ssd.py
>          volume = self.gamma * norm(embeddings[selection])
two RuntimeWarnings need to be deal with:
```
  /usr/local/lib/python3.9/site-packages/rsdiv/diversity/ssd.py:32: RuntimeWarning: invalid value encountered in divide
    selected_emb /= norm(selected_emb)

```

```
  /usr/local/lib/python3.9/site-packages/rsdiv/diversity/ssd.py:35: RuntimeWarning: invalid value encountered in multiply
    norms *= volume
```

2022-08-01 02:33 UTC, yinsn requested changes
minor fixes.

2022-08-01 22:54 UTC, yinsn approved these changes
LGTM!

2022-08-01 22:54 UTC, merged